# -*- coding: utf-8 -*-
"""Bank_Fraud_Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ul2kA6-_II1SLwwmuVw0xFc5IIXBGq4v
"""

import pandas as pd
import numpy as np

file = "Banking_Risk_Analytics_Dataset.xlsx"

customers = pd.read_excel(file, sheet_name="Customers")
accounts = pd.read_excel(file, sheet_name="Accounts")
transactions = pd.read_excel(file, sheet_name="Transactions")
fraud = pd.read_excel(file, sheet_name="FraudCases")
loans = pd.read_excel(file, sheet_name="Loans")
cards = pd.read_excel(file, sheet_name="Cards")
branches = pd.read_excel(file, sheet_name="Branches")



def audit(df, name):
    print(f"\n{name}")
    print("-" * 40)
    print("Rows:", df.shape[0])
    print("Columns:", df.shape[1])
    print("Null Values:")
    print(df.isnull().sum())
    print("\nDuplicates:", df.duplicated().sum())

audit(customers,"Customers")
audit(accounts,"Accounts")
audit(transactions,"Transactions")
audit(fraud,"FraudCases")
audit(loans,"Loans")
audit(cards,"Cards")
audit(branches,"Branches")

customers["CustomerID"].duplicated().sum()

accounts["AccountID"].duplicated().sum()

customers[
    (customers["CreditScore"] < 300) |
    (customers["CreditScore"] > 850)
]

customers[
    (customers["Age"] < 18) |
    (customers["Age"] > 100)
]

loans[loans["LoanAmount"] <= 0]

fraud[fraud["LossAmount"] <= 0]

invalid_accounts = accounts[
    ~accounts["CustomerID"].isin(customers["CustomerID"])
]

invalid_accounts.shape

invalid_loans = loans[
    ~loans["CustomerID"].isin(customers["CustomerID"])
]

invalid_cards = cards[
    ~cards["CustomerID"].isin(customers["CustomerID"])
]

invalid_fraud = fraud[
    ~fraud["TransactionID"].isin(transactions["TransactionID"])
]

customers.to_csv("clean_customers.csv",index=False)
accounts.to_csv("clean_accounts.csv",index=False)
transactions.to_csv("clean_transactions.csv",index=False)
fraud.to_csv("clean_fraud.csv",index=False)
loans.to_csv("clean_loans.csv",index=False)
cards.to_csv("clean_cards.csv",index=False)
branches.to_csv("clean_branches.csv",index=False)

